### PR TITLE
Separate runtime from build dependencies and remove build dependencies

### PR DESCRIPTION
**Pull request by vovimayhem**
Hi! How about shrinking the image size on this one, as we did with https://github.com/docker-library/redis , removing build dependency packages and leaving only runtime dependency packages?

I've already forked at https://github.com/vovimayhem/nginx-docker/tree/feature/shrink-image-size , and shrunk the image from 499.1 MB to 213.8 MB... but I think the Dockerfile is kinda messy...

What do you think?

### CODE REVIEW

**Comment by yosifkit** [comment]
This has exactly what I was going to look for today. I was slimming down the nginx build and needed the run time deps versus build deps. :+1: I am working on making nginx pull the source from a tarball rather than `ADD`ing it.  I'll incorporate these changes into mine and let you know when it is ready.

Thanks a ton. :cake:

**Comment by vovimayhem** [comment]
" I am working on making nginx pull the source from a tarball rather than ADDing it" 

I was wondering about that yesterday...

How about pulling the tarball with ADD?

That way, you won't need to install curl/wget on the container, at least not for pulling the code.

**Comment by yosifkit** [comment]
If you pull the source with `ADD`, you cannot delete it once you compile and install.  We already have packages to uninstall, might as well add curl to the list.

**Comment by yosifkit** [comment]
Ok, I have it up on my repo: https://github.com/infosiftr/nginx/blob/master/Dockerfile.

This brings the build to 173.3MB.

@vovimayhem, let me know what you think.  I used your lists, combining all the build and runtime dependencies into their respective lists, installing with the `--no-install-recommends` flag and then purge the build deps at the end.  IT runs but I have not done any extensive testing.

/cc @tianon for any comments on my Dockerfile.

**Comment by vovimayhem** [comment]
@yosifkit Looks good!

**Comment by yosifkit** [comment]
This was closed when I deleted the branch, but this has been incorporated into the new Dockerfile(s) in master branch.

**Comment by vovimayhem** [comment]
Excelente!

**Pull request closed without merging**
